default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: techteamdbad
  password: TcHemo0nCtI
  host: 192.168.153.175
  database: bewakoof_mar_12_dev

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default